#!/bin/sh
APPDIR=`dirname $0`;
java  -cp "$APPDIR/src:$APPDIR/bin:/opt/gwt-linux-1.3.3/gwt-user.jar:/opt/gwt-linux-1.3.3/gwt-dev-linux.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" de.willuhn.jameica.webadmin.gwt.WebAdmin/WebAdmin.html;
